import { RecordToolsService } from './record-tools.service';
import { FinanceLoanDirection, StockTransactionType } from '../../generated/prisma/client.js';

function makeService() {
  const prisma = {
    space: { findUnique: jest.fn().mockResolvedValue({ id: 'personal' }) },
    financeAccount: {
      findMany: jest.fn().mockResolvedValue([
        { id: 'a1', name: '現金' },
        { id: 'a2', name: '國泰世華' },
      ]),
    },
    stockTransaction: { findFirst: jest.fn().mockResolvedValue({ accountId: 'a2' }) },
    financeTransaction: {
      groupBy: jest.fn().mockResolvedValue([{ accountId: 'a1' }]),
      findFirst: jest.fn().mockResolvedValue({
        id: 't1',
        amount: 300,
        date: new Date('2026-09-30T00:00:00Z'),
        note: null,
        category: { name: '餐飲' },
        financeLoanId: 'loan1',
        loanRepaymentId: null,
        financeAdvanceId: null,
        advanceRepaymentId: null,
      }),
    },
  };
  const loans = { create: jest.fn(), addRepayment: jest.fn(), list: jest.fn() };
  const stockTransactions = { create: jest.fn() };
  const service = new RecordToolsService(
    prisma as never,
    loans as never,
    {} as never,
    {} as never,
    {} as never,
    {} as never,
    stockTransactions as never,
    {} as never,
    {} as never,
    {} as never,
  );
  return { service, loans, stockTransactions };
}

describe('RecordToolsService', () => {
  it('proposes a stock trade using the last settlement account, without writing', async () => {
    const { service, stockTransactions } = makeService();
    const out = (await service.execute('u1', 'propose_stock_trade', {
      type: 'BUY',
      stockCode: '0050',
      shares: 3000,
      pricePerShare: 152,
      date: '2026-10-01',
    })) as { pending: { kind: string; summary: string; data: Record<string, unknown> } };
    expect(out.pending.kind).toBe('stock_trade');
    expect(out.pending.summary).toBe('買進 0050 3,000 股，成交價 152，金額 456,000，交割帳戶「國泰世華」（2026-10-01）');
    expect(out.pending.data).toMatchObject({ type: StockTransactionType.BUY, accountId: 'a2', tradeDate: '2026-10-01' });
    expect(stockTransactions.create).not.toHaveBeenCalled();
  });

  it('runs a confirmed loan', async () => {
    const { service, loans } = makeService();
    const out = (await service.execute('u1', 'propose_loan', {
      direction: 'LEND',
      counterpartyName: '小明',
      amount: 3000,
      accountName: '現金',
      date: '2026-10-01',
    })) as { pending: Parameters<RecordToolsService['run']>[1] };
    expect(out.pending.summary).toBe('借出 3,000 給小明，從「現金」（2026-10-01）');
    await service.run('u1', out.pending);
    expect(loans.create).toHaveBeenCalledWith('u1', 'personal', {
      direction: FinanceLoanDirection.LEND,
      counterpartyName: '小明',
      amount: 3000,
      accountId: 'a1',
      date: '2026-10-01',
    });
  });

  it('refuses to delete a transaction generated by a loan', async () => {
    const { service } = makeService();
    await expect(service.execute('u1', 'propose_delete', { entity: 'transaction', id: 't1' })).rejects.toThrow(
      '借貸／代墊產生的',
    );
  });

  it('rejects an unknown account name with the valid options', async () => {
    const { service } = makeService();
    await expect(
      service.execute('u1', 'propose_advance', { title: '材料費', amount: 5000, accountName: '玉山' }),
    ).rejects.toThrow('可用的：現金、國泰世華');
  });
});
